name: 'RTL:syn_TSMC65'
description: 'synthesize the design using VCS TSMC65 and generate report'
author: 'Boyul Choi <gju06051@gmail.com>'

runs:
  using: composite
  steps:
    - run: |
        source ${{github.workspace}}/env.source ${{github.workspace}}
        ${{github.workspace}}/rtl-actions/bin/action.syn_TSMC65
      shell: bash
