name: 'RTL:lint'
description: 'Lint test (checking programmatic and stylistic errors) using Synopsys Spyglass with sign-off rules'
author: 'Jungrae Kim <dale40@gmail.com>'

inputs:
  filelist:
    description: "The path to the filelist containing all the design file. The path is relative to the root of the repository"
    type: string
    required: false
  top:
    description: "The name of the top-level design"
    type: string
    required: false
    
runs:
  using: composite
  steps:
    - run: rtl-actions/bin/action.lint \
           ${{ inputs.filelist  && '--filelist inputs.filelist' || '' }} \
           ${{ inputs.top && '--top inputs.top' || '' }}
      shell: bash
