name: 'RTL:syn-report'
description: 'print the synthesized design report to github action console'
author: 'Boyul Choi <gju06051@gmail.com>'

runs:
  using: composite
  steps:
    - name: Report (Design)                     
      run: cat ${{github.workspace}}/work.syn/*.design.rpt
      shell: bash
    - name: Report (Timing)
      run: cat ${{github.workspace}}/work.syn/*.timing.rpt
      shell: bash
    - name: Report (Area)
      run: cat ${{github.workspace}}/work.syn/*.area.rpt
      shell: bash
    - name: Report (Power)
      run: cat ${{github.workspace}}/work.syn/*.power.rpt
      shell: bash
