name: 'RTL:syn-report'
description: 'print the synthesized design report to github action console'
author: 'Boyul Choi <gju06051@gmail.com>'

# Inputs of the action
inputs:
  out:
    description: "The output file path"
    required: false
    default: $${{github.workspace}}/work.syn
    type: string

runs:
  using: composite
  steps:
    - name: Report (Design)                     
      run: cat ${{github.workspace}}/${{inputs.out}}/*.design.rpt
      shell: bash
    - name: Report (Timing)
      run: cat ${{github.workspace}}/${{inputs.out}}/*.timing.rpt
      shell: bash
    - name: Report (Area)
      run: cat ${{github.workspace}}/${{inputs.out}}/*.area.rpt
      shell: bash
    - name: Report (Power)
      run: cat ${{github.workspace}}/${{inputs.out}}/*.power.rpt
      shell: bash
